### ISSUE TITLE
32 bit process, loading 64 bit module failure

### ISSUE THREAD

**Issue by nihuai** [ez8-co/yapi#1]
DWORD64 WINAPI LoadLibrary64(const TCHAR* filePath)
	{
		static X64Call LdrLoadDll("LdrLoadDll");
		if (!LdrLoadDll) return 0;

		DWORD64 module = 0;
		DWORD64 status = LdrLoadDll(0, 0, filePath, &module);
		if (!status) return module;

		SetLastError64(status);
		return NULL;
	}

1
//There seems to be a mistake in the source code.
//The function should initialize the string.（LdrLoadDll）
RtlInitUnicodeString(A,B); 
LdrLoadDll(0, 0,A,x);
2
32 bit process, loading 64 bit module failure

The 32 bit process can load 64 bit modules.
I can't do it. I'm looking for a solution.
yapi and wow64ext， it still won't solve the problem

**Comment by orca-zhang** [comment]
Sorry for not testing the `LoadLibrary64` function that inspired from other enhanced `wow64ext`s.

I think you'd like to see the example below:

> Popular `LoadLibrary` example
> 
> ```
>     YAPICall LoadLibraryA(hProcess, _T("kernel32.dll"), "LoadLibraryA");
>     DWORD64 x86Dll = LoadLibraryA("D:\\x86.dll");
>     DWORD64 x64Dll = LoadLibraryA.Dw64()("D:\\x64.dll");
>     _tprintf(_T("X86: %I64x\nX64: %I64x\n"), x86Dll, x64Dll);
> ```

If failed all the same, check the errcode and post it here again.

Thanks for you kind feedback.

Looking forward to your further reply.

Orca

**Comment by orca-zhang** [comment]
I'll **REMOVE** the deprecated `LoadLibrary64` ASAP.
